#!/bin/sh

# PROVIDE: rtorrent-flood
# REQUIRE: rtorrent
# KEYWORD: shutdown

. /etc/rc.subr

name="rtorrent_flood"
desc="rTorrent Flood Daemon"
rcvar="rtorrent_flood_enable"
pm2="/usr/local/bin/pm2"
workdir="/home/rtorrent/flood"
script="dist/index.js"

start_cmd="${name}_start"
stop_cmd="${name}_stop"

rtorrent_flood_start() {
  NODE_ENV=production
  su - root -c "exec ${pm2} start ${workdir}/${script}"
}

rtorrent_flood_stop() {
  su - root -c "exec ${pm2} stop ${workdir}/${script}"
}

load_rc_config $name
run_rc_command "$1"

