#!/bin/sh

# PROVIDE: rtorrent-flood
# REQUIRE: rtorrent
# KEYWORD: shutdown

. /etc/rc.subr

name="rtorrent_flood"
desc="rTorrent Flood Daemon"
rcvar="rtorrent_flood_enable"
forever="/usr/local/bin/node /usr/local/bin/forever"
pm2="/usr/local/bin/pm2"
workdir="/home/rtorrent/flood"
script="dist/index.js"

start_cmd="${name}_start"
stop_cmd="${name}_stop"

rtorrent_flood_start() {
  NODE_ENV=production
  DEV_SERVER_PORT=80
  DEV_SERVER_HOST=0.0.0.0
  #su - root -c "exec ${forever} start -a -l ${workdir}/forever.log -o ${workdir}/output.log -e ${workdir}/error.log -p /var/run/forever --workingDir ${workdir} --sourceDir ${workdir} ${script}"
  su - root -c "exec cd ${workdir} ${pm2} start ${script}
}

rtorrent_flood_stop() {
  su - root -c "exec ${forever} --workingDir ${workdir} --sourceDir ${workdir} stop ${script}"
}

load_rc_config $name
run_rc_command "$1"
